# Generated by Django 4.2.15 on 2024-10-24 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blogtag",
            table="blog_tag",
        ),
    ]
