# Generated by Django 4.2.15 on 2024-10-24 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("promotion", "0001_initial"),
        ("my_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("product_type", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("member_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("gallery", models.TextField()),
                ("weight", models.FloatField()),
                ("diameter", models.FloatField()),
                ("dimensions", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delete_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="my_admin.myadmin",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.catalog",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="promotion.promotion",
                    ),
                ),
            ],
        ),
    ]
